### ISSUE TITLE
Does Not Produce True Centroid if Points Are Not Evenly Dispersed

### ISSUE THREAD

**Issue by hallahan** [Turfjs/turf-centroid#1]
If you had a polygon with thousands of points on the left side and only several on the right side, the center that gets calculated would not be in the actual center of the shape.

This is what I use to calculate a centroid that solves this problem:
```js
function area(partArr) {
  var area = 0;
  var len = partArr.length;
  for (var i = 0, j = len - 1; i < len; j=i, i++) {
    var p1 = partArr[j];
    var p2 = partArr[i];

    area += p1.x * p2.y - p2.x * p1.y;
  }

  return area / 2;
}

/*
    NH TODO: We are indeed getting the centroid, but ideally we
    want to check if the centroid is actually within the polygon
    for the polygons that bend like a boomarang. If it is outside,
    we need to nudge it over until it is inside...
 */
function centroid(partArr) {
  var len = partArr.length;
  var x = 0;
  var y = 0;
  for (var i = 0, j = len - 1; i < len; j=i, i++) {
    var p1 = partArr[j];
    var p2 = partArr[i];
    var f = p1.x * p2.y - p2.x * p1.y;
    x += (p1.x + p2.x) * f;
    y += (p1.y + p2.y) * f;
  }
  f = area(partArr) * 6;
  return L.point(x/f, y/f);

}
```

http://en.wikipedia.org/wiki/Centroid#Centroid_of_polygon

**Comment by morganherlocker** [comment]
This is the intended behavior for turf-centroid. I believe what you are looking for is [turf-center](https://github.com/Turfjs/turf-center), which ignores density, and just calculates the center of the bounding box. It does not do the 'nudging' like your code does though. That is pretty neat.

**Comment by hallahan** [comment]
I'm working on calculating centroids for vector tile polygons so that i can put a label on it. It's helpful to have this done on the fly in the client because a) You don't have to have to deal with PostGIS to figure this out and b) the centroid is calculated with the tiles loaded in the viewport rather than the complete feature.

This solves the problem where if you are looking at the United States, but only one region, you only see a label, and that is positioned properly based on the client's view.

Once I'm finished with this, I'll have to roll the centroid logic into here. Getting the center of a bounding box isn't exact enough for this kind of thing.

**Comment by morganherlocker** [comment]
hmm, we could add this nudging as an optional flag (in the turf-center module). There are still reasons to not have an arbitrary nudging, especially in spatial stats, so I want to go with the option of least surprise for the default.

**Comment by morganherlocker** [comment]
we also have [turf-point-on-surface](https://github.com/Turfjs/turf-point-on-surface) now, which guarantees the centroid will be on the polygon. There are hundreds of ways to calculate a centroid, so I think we will leave the rest of them to userland for now.
