### ISSUE TITLE
Geometric mean?

### ISSUE THREAD

**Issue by jseppi** [Turfjs/turf-centroid#4]
The docstring says that this calculates the centroid using the geometric mean, but the code is calculating the arithmetic mean.

**Comment by morganherlocker** [comment]
@jseppi thanks, I was misunderstanding the terms. I'll update the docs.

**Comment by morganherlocker** [comment]
done https://github.com/Turfjs/turf-centroid/commit/acd86ada4d7d34cee3a486733ba3bfbdc4a821db
