### ISSUE TITLE
Result is off-center because start point is counted twice

### ISSUE THREAD

**Issue by mgax** [Turfjs/turf-centroid#6]
The algorithm iterates over all points in the polygon. The start point and end point are the same, so the result is weighted toward that point. This is clearly visible in the [documentation example](http://turfjs.org/static/docs/module-turf_centroid.html). Maybe this should be fixed in `turf-meta`?

**Comment by morganherlocker** [comment]
thanks @mgax. fixed in 1.0.3 https://github.com/Turfjs/turf-centroid/commit/6bc1a34b019f3251efe5ec20a5d6f77f37e6b196
